### ISSUE TITLE
贵司这个项目不是开源的？不供外人使用，是吧？

### ISSUE THREAD

**Issue by web525** [Tinywan/html5-dash-hls-rtmp#1]
贵司这个项目不是开源的？不供外人使用，是吧？

**Comment by Tinywan** [comment]
@web525 没有，这里只是思路以及播放的Demo

**Comment by web525** [comment]
哦，谢谢，我们正在找一款可以支持在IE9下播放rtmp和m3u8的兼容方案，目前也用的aliplayer的vue版本，但是发现它在IE9下面与我们的webSocket的IE9兼容方案有冲突，目前还在搞……

**Comment by Tinywan** [comment]
建议你不要做`IE10`及以下的解决方案！
