### ISSUE TITLE
现在浏览器不支持flash了，请问还能播放rtmp么？

### ISSUE THREAD

**Issue by sameenzm** [Tinywan/html5-dash-hls-rtmp#9]
现在浏览器不支持flash了，请问还能播放rtmp么？有什么方案能支持播放rtmp 的流呢？

**Comment by sameenzm** [comment]
现在浏览器不支持flash了，请问还能播放rtmp么？
![Uploading image.png…]()

**Comment by Tinywan** [comment]
@sameenzm 现在基本都是跑的 m3u8。如果要播放RTMP基本都在移动端了，例如：微信小程序就是支持RTMP播放的
